"""英文閱讀策略的說明（STRATS）與例題解析（EXPLAIN）。

STRATS[代碼]：name 名稱、en 英文名稱、one 一句話說明、signals 看到這些就用、steps 操作步驟、traps 常見陷阱、check 自我檢核
EXPLAIN[題號]：why 解析；示範題另有 demo（依策略步驟的解題過程）
解析為本站自行撰寫，答案以官方公布為準。
"""

STRATS = {
    "E1": {"name": "掃讀找細節", "en": "Scanning",
           "one": "先看題目抓關鍵字（人名、數字、時間、地點），再回文章快速找到那一句，逐字比對。",
           "signals": ["According to the passage / notice, which is true?", "What do we know about …?",
                       "When / Where / How much …?", "Which is NOT mentioned / NOT true?"],
           "steps": ["圈出題目和選項中的關鍵字：數字、名稱、時間、條件。",
                     "用關鍵字回到文章掃讀，找到對應的句子。",
                     "把那一句和選項逐字比對：主詞、數字、條件是否一致。",
                     "NOT 題：每個選項都要找到出處，找不到或說法相反的就是答案。"],
           "traps": "最常見的是張冠李戴（把 A 的資訊套到 B），以及「用了文中的字、意思卻被改了」的選項。",
           "check": ["我會先看題目，再回文章找答案。", "我選的答案都能在文中畫出依據。", "我會核對數字、時間和條件是否完全相同。"]},
    "E2": {"name": "略讀抓主旨", "en": "Skimming",
           "one": "讀標題、第一段和每段第一句，找出全文反覆談的主題，選涵蓋全文、不大也不小的選項。",
           "signals": ["What is the passage mainly about?", "Which is the best title for the passage?",
                       "Which idea is talked about in the first paragraph?", "What is the main idea of paragraph 2?"],
           "steps": ["先讀標題、第一段和每段的第一句。",
                     "找出反覆出現的關鍵詞，那就是主題。",
                     "用一句話說出「這篇（這段）在講 ___ 的 ___」。",
                     "刪掉只講一個細節（太小）或範圍太大、文章沒談到的選項。"],
           "traps": "以偏概全：選了只在某一句出現的細節；或選了範圍太大、文章沒有談到的說法。",
           "check": ["我會先略讀，掌握每一段在說什麼。", "我能用一句話說出全文主旨。", "我會分辨「主旨」和「細節」。"]},
    "E3": {"name": "上下文猜字義", "en": "Context Clues",
           "one": "不認識的字不用慌：看前後句的解釋、例子、對比或因果，推出它在這裡的意思，再代回句子檢查。",
           "signals": ["What does the word “…” mean in the reading?", "Which is closest in meaning to “…”?",
                       "文章中加引號、畫線或粗體的字詞"],
           "steps": ["找到那個字所在的句子，再讀前後各一句。",
                     "找線索：同義解釋（that is、or）、舉例（such as）、對比（but、unlike）、因果（so、because）。",
                     "先用中文猜出意思，再看選項。",
                     "把選項代回原句，讀起來通順、合乎上下文才選。"],
           "traps": "選了這個字最常見的意思，而不是它在這篇文章裡的意思；或只看單字、不看上下文。",
           "check": ["遇到生字，我會先找上下文的線索。", "我會把選項代回原句檢查。", "我知道同一個字在不同文章裡意思可能不同。"]},
    "E4": {"name": "指涉與同義改寫", "en": "Reference & Paraphrase",
           "one": "遇到 it、they、this、the artist 等指涉詞，往前找它代替的人、物或事；選項常把原文換句話說，要認得出來。",
           "signals": ["What does the highlighted “they / this practice” refer to?",
                       "Which is NOT used in the reading to mean …?", "選項的用字和原文不同，意思卻相同"],
           "steps": ["找到指涉詞，看它是單數還是複數、指人還是指物。",
                     "往前找最近、而且條件符合的名詞，或前面說過的整件事。",
                     "把找到的答案代回原句，意思要通順。",
                     "比對選項時認得「換句話說」：意思相同、用字不同。"],
           "traps": "張冠李戴：選了離指涉詞最近、但單複數或意思不合的名詞。",
           "check": ["我會注意指涉詞的單複數。", "我會把答案代回原句檢查。", "我認得出原文被換句話說的選項。"]},
    "E5": {"name": "推論言外之意", "en": "Inference",
           "one": "答案不會直接寫在文中，要把兩個以上的線索連起來，推出「一定成立」的結論，但不能推太遠。",
           "signals": ["What can be inferred from the passage?", "What do we know about … from the dialogue?",
                       "When would it be dangerous …?", "Why did … say …?"],
           "steps": ["找出跟題目有關的線索句：人物的反應、條件、結果。",
                     "把線索連起來：「因為文中說……，所以可以推知……」。",
                     "檢查每個選項有沒有文中線索支持。",
                     "刪掉推太遠、只是常識，或和文意相反的選項。"],
           "traps": "過度推論：選項聽起來合理，但文中沒有足夠的證據；或用自己的常識代替文章。",
           "check": ["我的推論都能指出文中的線索。", "我會刪掉推太遠的選項。", "我不會用常識代替文章內容。"]},
    "E6": {"name": "作者目的與態度", "en": "Purpose & Tone",
           "one": "問「作者為什麼這樣寫」：舉例、比喻、引用、列清單都有目的；態度題看作者的評價字和結尾。",
           "signals": ["Why does the writer talk about …?", "What can be a reason why … is put in …?",
                       "Which best describes the author’s attitude toward …?"],
           "steps": ["找到題目說的那一段、那個例子或那張表。",
                     "看它前後在說什麼主張：例子和比喻是用來支持這個主張的。",
                     "態度題：圈出作者的評價字（promising、unfortunately、should）和結尾的看法。",
                     "選說出「目的」的選項，不選只重述內容的選項。"],
           "traps": "字面相符：選項重複了例子的內容，卻沒說出作者的目的；或把文中人物的情緒當成作者的態度。",
           "check": ["我會問自己：作者為什麼放這個例子？", "我會找作者的評價字判斷態度。", "我會分辨「內容」和「目的」。"]},
    "E7": {"name": "篇章結構與轉折", "en": "Structure & Transitions",
           "one": "看懂句子之間的關係（舉例、轉折、因果、換句話說、時間順序），用轉折語和段落結構判斷該接什麼。",
           "signals": ["克漏字選 however、for example、in other words 等轉折語", "篇章結構題：把句子放回文章",
                       "How is the passage organized?"],
           "steps": ["讀空格前後各一句（或段落的頭尾）。",
                     "判斷兩句的關係：同方向（補充、舉例、換句話說）、反方向（轉折、讓步），還是因果？",
                     "選符合這個關係的轉折語或句子。",
                     "代回去讀一遍，前後要接得順。"],
           "traps": "關係倒置：把轉折看成因果、把舉例看成結論；或只看空格後面、不看前面。",
           "check": ["我會先判斷前後兩句的關係。", "我認得常見轉折語的功能。", "選完我會把整段讀一遍。"]},
    "E8": {"name": "圖表與實用文本", "en": "Charts & Practical Texts",
           "one": "告示、菜單、時刻表、地圖、圖片題：先列出題目的條件，再到圖表裡逐項對照，需要時動手計算。",
           "signals": ["題目附有 notice、menu、schedule、map、chart 或圖片", "Which is the earliest time …?",
                       "How much did they pay?", "Which is the closest illustration of …?"],
           "steps": ["讀題目，列出所有條件：誰、要什麼、哪一天、幾點。",
                     "在圖表中找到每個條件對應的位置。",
                     "需要計算就寫下算式，注意附註（*Friday only、折扣、公休日）。",
                     "用答案回頭檢查，每個條件都要符合。"],
           "traps": "看錯列，或漏掉小字附註（只限某天、會員限定），計算時漏算或多算一項。",
           "check": ["我會先列出題目的所有條件。", "我會看圖表的附註和小字。", "需要計算時我會寫下算式。"]},
    "E9": {"name": "詞性先篩選字", "en": "Part of Speech First",
           "one": "文意選填先看空格需要的詞性（名詞、動詞、形容詞、副詞），把十個選項分組，再依意思選字。",
           "signals": ["學測文意選填：一篇文章十個空格、十個選項 (A)–(J)"],
           "steps": ["先把十個選項依詞性分組：名詞（單複數）、動詞（時態）、形容詞、副詞。",
                     "看空格前後：the ___ that → 名詞；was ___ → 形容詞或分詞；主詞 ___ 受詞 → 動詞。",
                     "在同詞性的選項裡，用上下文的意思決定。",
                     "用過的選項劃掉，最後檢查時態和單複數。"],
           "traps": "形近義混：只憑意思選字，忽略詞性、時態或單複數不合。",
           "check": ["我會先把選項依詞性分組。", "我會從空格前後判斷需要的詞性。", "我會檢查時態和單複數。"]},
    "E10": {"name": "語境線索選字", "en": "Vocabulary in Context",
            "one": "詞彙題先遮住選項，讀整句找線索（因果、對比、解釋），自己想一個意思，再找最接近的選項。",
            "signals": ["會考字彙題、學測詞彙題：一句話一個空格，四個選項通常詞性相同"],
            "steps": ["遮住選項，先讀完整個句子。",
                      "找線索字：because、so、but、never 等，看前後是因果還是對比。",
                      "用中文先填空，例如「不借她錢是 ___ 的」。",
                      "找意思最接近的選項，並確認常見搭配（例如 as a penalty）。"],
            "traps": "形近義混或關係倒置：選了意思相近但不合句意的字，或把因果看反了。",
            "check": ["我會先讀完整句再看選項。", "我會找出句子裡的線索字。", "我會注意單字的常見搭配。"]},
    "E11": {"name": "克漏字通篇理解", "en": "Cloze in Context",
            "one": "綜合測驗不能只看空格那一句：先掌握全文主題，再用前後文的意思和常見搭配選答案。",
            "signals": ["學測綜合測驗：一篇短文五個空格，選項多為單字或片語"],
            "steps": ["先快速讀完全文，知道主題。",
                      "回到空格，讀前後句，想想這裡要表達什麼。",
                      "注意搭配：動詞＋受詞、形容詞＋名詞、片語動詞。",
                      "代回整段讀一遍，意思要合乎全文主題。"],
            "traps": "只看空格附近幾個字就選，選到搭配看似可以、但不合全文意思的選項。",
            "check": ["我會先讀完全文再作答。", "我會注意前後文和全文主題。", "我會檢查單字和片語的搭配。"]},
    "E12": {"name": "句型與文法", "en": "Grammar Structure",
            "one": "先分析句子結構：主詞、動詞、時間線索、句型規則（allow＋受詞＋to V），再決定動詞形式或詞性。",
            "signals": ["四個選項是同一個字的不同形式（jump / to jump / jumping / jumped）", "考時態、分詞、關係詞、比較級"],
            "steps": ["看四個選項的差別：時態？詞性？分詞？",
                      "找出句子的主詞和主要動詞，判斷空格扮演什麼角色。",
                      "找時間線索（yesterday、when…）或句型規則（allow sb to V、被動用過去分詞）。",
                      "代回整句，檢查時態和主動被動是否一致。"],
            "traps": "詞性語法不合：只看意思、不看句子結構；忽略時間線索而用錯時態。",
            "check": ["我會先比較四個選項的差別。", "我會找出主詞、動詞和時間線索。", "我會檢查主動或被動。"]},
}

EXPLAIN = {
    # E1 掃讀找細節
    "K113-25": {"why": "告示下方寫 All breads at half price after 8pm（週末 after 7pm），而營業時間平日到 9pm、週末到 8pm，都是打烊前一小時半價。(A) 一週營業七天；(C) 可頌和蝴蝶餅只有週五才有；(D) 是付 $100 成為會員，不是省 $100。",
                "demo": ["關鍵字：open five days、half price、weekends、members $100。",
                         "回告示找到 Business hours、half price after 8pm (after 7pm on Saturdays and Sundays) 和會員說明。",
                         "比對：平日 9pm 打烊、8pm 半價；週末 8pm 打烊、7pm 半價，都是打烊前一小時，(B) 正確。",
                         "其他選項：Mon. to Fri. 和 Sat. & Sun. 都營業，(A) 錯；croissants、pretzels 標 *Friday only，(C) 錯；$100 是會員費，(D) 錯。"]},
    "X108-54": {"why": "文中說 Once the pests detect the chemical fog, they’ll hide themselves in walls or other hideaways，臭蟲會躲到安全的地方，就是 retreat to safe places。"},
    "K111-37": {"why": "文中說 It’s best to plan one day for one part of the trail，建議一天走一段步道。側步道太窄不能騎車，露營只能在少數營地，(A)(B) 都不對；文中也沒有建議早上去博物館。"},
    # E2 略讀抓主旨
    "K111-27": {"why": "第一段說明 Tabata 的做法：運動 20 秒、休息 10 秒、重複至少八次，動作可以自己選。最佳時間、發明者都沒提到；「重複八次」是一回訓練的做法，不是多久練一次。",
                "demo": ["先讀第一段的第一句和整段：在介紹 Tabata training。",
                         "反覆出現的是 exercise 20 seconds、rest 10 seconds、moves：都在說「怎麼做」。",
                         "一句話：第一段在講 Tabata 訓練的做法。",
                         "(B) 最佳時間、(C) 誰發明、(D) 多久做一次，第一段都沒談到，選 (A)。"]},
    "X109-45": {"why": "全文從船長進港前交棒說起，接著介紹 marine pilot 的專業知識、挑戰（淺灘、潮汐、風）和責任，都在介紹「引水人」這個特殊職業。航運貿易、靠港規範和海洋保護都只是文中提到的一部分。"},
    "X108-53": {"why": "文章先說很多人用煙霧彈殺蟲，接著說 quite the opposite is true，研究發現 little—if any—effect，最後建議交給專業人員。全文重點是煙霧彈沒什麼效果（ineffectiveness）。"},
    # E3 上下文猜字義
    "K115-23": {"why": "漫畫裡選班長沒人選他、當業務兩個月只賣出一台車被開除，每次之後都說 I bombed it，可知 bombed 是「搞砸、失敗」。",
                "demo": ["找到 bombed 出現的格子：I totally bombed it.、I bombed it again.",
                         "線索：說了不可能的政見、沒被選上；說要賣 50 台車，兩個月只賣 1 台，被說 we don’t need your service anymore。",
                         "先用中文猜：兩次都是結果很糟，bombed＝失敗、搞砸。",
                         "代回去：I totally failed at it. 通順，選 (B)。"]},
    "X107-49": {"why": "arid 前面說臺灣大部分地區有足夠的淡水，But 轉折後說在 arid regions such as Saudi Arabia 淡水短缺、水資源有限，可知 arid 是「乾燥的」。"},
    "K111-38": {"why": "There are two types of lodging for visitors 之後介紹露營和住旅館，兩種都是過夜的地方，可知 lodging 是住宿處。"},
    # E4 指涉與同義改寫
    "K115-28": {"why": "her visitor、the little singers、her garden friends 都指夜鶯；At first, the artist was playing alone 的 the artist 是在演奏的 Harrison 本人，夜鶯在最後十五分鐘才開始唱。",
                "demo": ["題目問哪一個「不是」指夜鶯，要逐一找出四個詞在文中的位置。",
                         "a visitor she did not expect. The visitor was a nightingale → her visitor 指夜鶯；more people should hear the little singers → 也指夜鶯；played on the radio with her garden friends → 也指夜鶯。",
                         "代回原句：At first, the artist was playing alone，接著說夜鶯後來才加入，所以 the artist 是演奏大提琴的 Harrison。",
                         "四個詞都換句話說了，只有 the artist 指的不是夜鶯，選 (C)。"]},
    "X110-52": {"why": "they could nest together from largest to smallest：能從大到小套在一起的，是前面說的大小、厚度都不同的玻璃半球（hemispheres），不是鐵棒。"},
    "X107-42": {"why": "this practice 前面講 Jefferson 開始在就職日開放白宮（inaugural open house），後來人潮太多、造成安全問題，要解決的就是「就職日開放參觀」這個做法。"},
    # E5 推論言外之意
    "K112-32": {"why": "文章最後說 If the mosquito flies too low when it is hit by the raindrop, it won’t have time to fly off，就會撞到地面而死，所以飛得太低時最危險。",
                "demo": ["找線索句：However, this trick isn’t always successful. 後面說明什麼情況會失敗。",
                         "連起線索：蚊子要跟著雨滴落下約 6 公分才能滾開飛走 → 如果飛得太低，還沒來得及脫身就撞到地面。",
                         "檢查選項：(B)(C) 文中說蚊子很輕，被打到也不會死；(D) 落下 6 公分正是脫身的過程，不是危險的原因。",
                         "有文中線索支持的是 (A)。"]},
    "K114-22": {"why": "Jenny 宣布要結婚，Mark 卻馬上說自己找到工作；Linda 說 You’re stealing Jenny’s thunder，最後還大叫 MARK!!，可知 Mark 讓 Linda 不開心。Mark 已經找到工作，(B) 錯；要結婚的是 Jenny，不是和 Mark。"},
    "X113-42": {"why": "文中說 Moran 的水彩是 the first color renderings of the area，同行的攝影師 Jackson 的照片不算彩色圖像，可以推知當時彩色照片並不普遍。"},
    # E6 作者目的與態度
    "K113-30": {"why": "作者說陳老闆把自己看成醫生，書像人一樣會生病；大圖書館、博物館像醫院，陳老闆的書店像健康中心，處理比較小的問題。這個比喻是用來說明陳老闆提供的服務。",
                "demo": ["找到題目說的段落：第二段 Chen sees himself as a doctor … Chen’s bookstore is a health center.",
                         "看前後的主張：陳老闆修補有小問題的書，大圖書館修補嚴重損壞的古書。",
                         "比喻的目的：用「醫院／健康中心」說明他的工作是什麼、和大圖書館有什麼不同。",
                         "(B) 未來計畫、(C) 愛書、(D) 書店的重要都不是這段的重點，選 (A)。"]},
    "X107-52": {"why": "最後一段說海水淡化越來越有吸引力，各方正努力尋找更便宜、乾淨、節能的方法，而且 promising new findings are being reported，作者的態度是充滿希望（hopeful）。"},
    "K111-24": {"why": "清單列出冰淇淋、柳橙汁、可樂等常見食物飲料藏了多少糖，對照上方建議的每日用量，是提醒我們常在不知不覺中吃進太多糖。糖對身體的影響在另一區塊說明。"},
    # E7 篇章結構與轉折
    "X107-29": {"why": "空格前說清醒夢讓你運用大腦未使用部分的能力，空格後說它是讓你在睡覺時好好運用大腦深處的方法，兩句意思相同，是換句話說：In other words。",
                "demo": ["讀空格前後：前句 It is your chance to play around with the extraordinary abilities buried in unused parts of your brain；後句 it is a way for you to put the deepest areas of your brain to good use。",
                         "判斷關係：兩句都在說「運用大腦沒用到的部分」，同方向、意思相同，是換句話說。",
                         "符合「換句話說」的是 In other words；On the contrary 是相反，By no means 是絕不。",
                         "代回去讀：In other words, it is a way … 前後通順，選 (A)。"]},
    "K111-40": {"why": "空格前說明 palindrome 是正讀反讀都一樣的字或句子，空格後列出 “eye”、“Bob” 等例子，所以用 for example。"},
    "X109-28": {"why": "前一句說科學家認為沒有證據證明 Blue Monday 讓人比較難過，後一句卻說這個觀念仍然存在，前後是轉折關係，用 And yet（然而）。"},
    # E8 圖表與實用文本
    "K113-24": {"why": "四種麵包的出爐時間：white bread 10:30am、farm bread 4:30pm、bagels 11:30am、challah 3:30pm。要全部買到，至少要等到最晚出爐的 farm bread（4:30pm），選項中最早的是 5:00pm。",
                "demo": ["列條件：Kevin 要買 white bread、farm bread、bagels、challah 四種，問「全部買得到」的最早時間。",
                         "在表中找時間：white bread 10:30am、bagels 11:30am、challah 3:30pm、farm bread 4:30pm。",
                         "全部都要買到，就要等最晚的 farm bread 4:30pm 出爐；11:00am、4:00pm 都太早。",
                         "4:30pm 以後最早的選項是 5:00pm，選 (C)；7:00pm 也買得到，但不是最早。"]},
    "K112-24": {"why": "兩份 Garden Sandwich $80×2＝$160，Autumn Wind $60、Winter Snow $70。集滿 15 顆星可以免費換一杯 $60 的飲料，Autumn Wind 免費，所以付 $160＋$70＝$230。"},
    "X110-49": {"why": "文中說玻璃半球從大到小套在一根鐵棒上，連到像紡車的裝置，用腳踏板轉動。(D) 有一排由大到小的玻璃碗、轉輪和踏板，最接近；(A) 是一杯杯的玻璃杯，(B) 是編鐘，(C) 是紡紗機。"},
    # E9 詞性先篩選字
    "X108-38": {"why": "The reason was ___ 空格在 be 動詞後面，需要形容詞；接著冒號說明理由：爸爸什麼都不會記得，所以「理由很明顯」，選 obvious。",
                "demo": ["先把選項分組：形容詞 ready、obvious；副詞或形容詞 little；名詞 purchases、requests、privilege；過去式或分詞 trusted、insisted、ruined、revealed。",
                         "看空格前後：The reason was ___ : → be 動詞後面接形容詞或分詞。",
                         "看意思：冒號後說 Dad would not remember any of it，是一個大家都知道的理由，「理由很明顯」最合理。",
                         "形容詞中 obvious 合乎句意，選 (J)。"]},
    "X108-34": {"why": "the ___ that he made：冠詞 the 後面要接名詞，而且 make purchases 是「買東西」的常見搭配；爸爸憑記憶買東西，所以選 purchases。"},
    "X108-31": {"why": "This often ___ their anniversary celebration：主詞後面需要動詞，故事用過去式；爸爸記錯日子，花總是晚一個月送到，所以「毀了」週年慶祝，選 ruined。"},
    # E10 語境線索選字
    "K111-14": {"why": "後句說 Amy 借了錢從來不還，所以不借她錢是「明智的」（wise）。crazy、wrong 和句意相反，helpful 也不合。",
                "demo": ["遮住選項，讀完兩句：You were ___ not to lend Amy money. She never gives back what she borrows.",
                         "線索：第二句說明原因：她借了從來不還。",
                         "先用中文填空：「不借她錢是 ___ 的」→ 聰明、明智的。",
                         "選項中意思最接近的是 wise，選 (C)。"]},
    "X107-13": {"why": "遲交作業會被打低分，這是一種「懲罰」，as a penalty 是常見搭配。hardship 是困苦，bargain 是便宜貨，comment 是評論。"},
    "K111-12": {"why": "颱風走了還是看不到太陽，因為新聞說更大的雨很快就會「接著來」，用 follow。catch、move、stop 都不合句意。"},
    # E11 克漏字通篇理解
    "X107-23": {"why": "全文在說用頭髮和動物毛吸油，處理漏油事件。clean up after oil spills 是「清理（漏油）造成的污染」，其他片語是逃過懲罰、用完、看不起，都不合。",
                "demo": ["先讀全文：頭髮會吸油，Matter of Trust 收集頭髮和動物毛，做成墊子去吸海上的漏油。",
                         "回到空格：collected donations of human hair and animal fur to ___ the thousands of oil spills，這裡要說「處理、清理」漏油。",
                         "看搭配：clean up after something＝在事情發生後清理善後，和 oil spills 搭配合理。",
                         "代回去：…to clean up after the thousands of oil spills that happen each year. 合乎全文主題，選 (B)。"]},
    "X107-22": {"why": "the ultimate renewable ___: human hair, of which there is an unlimited supply：頭髮取之不盡，是可再生的「資源」，renewable resource 是常見搭配。"},
    "X107-25": {"why": "每天剪下大量頭髮和動物毛，組織收集的是這些「剪下來、不需要的」毛髮，選 unneeded；後文的 leftover hair and fur 也是同樣的意思。"},
    # E12 句型與文法
    "K111-13": {"why": "when I got home 是過去某個時間點，那時哥哥「正要」出門吃晚餐，還邀我一起去，用過去進行式 was going out。",
                "demo": ["比較選項：goes out、went out、has gone out、was going out，考的是時態。",
                         "找時間線索：Yesterday when I got home from work，是過去某一個時間點。",
                         "那個時間點哥哥正在做的事（正要出門），而且接著還邀我一起去，所以他還沒離開。",
                         "過去某一刻正在進行的動作用過去進行式，選 (D)。"]},
    "X109-24": {"why": "allow＋受詞＋to V（允許某人或某物做某事）：This energy allowed the water to jump into the air，選 to jump。"},
    "X107-24": {"why": "空格修飾名詞 waters，水是「被污染的」，用過去分詞 polluted 當形容詞：sent to polluted waters（送到被污染的水域）。"},
}
